library(glmbayes)
a<-cmb_augment(matrix(1,2,1),c(1,2),c(4,4))
f<-list(family=cmb(),x=a$x,prior.weights=a$weights,coefficients=matrix(c(0,1),1),offset=c(1,1,.5,.5),offset2=c(1,1,.5,.5))
j<-0:4;lw<-j+1.5*lchoose(4,j);expected<-sum(j*exp(lw-max(lw)))/sum(exp(lw-max(lw)))
cat('nonzero offsets: fitted counts',cmb_fitted(f,'count'),'expected',expected,'\n')
cat('nu with offset: returned',cmb_nu(f),'expected 1.5\n')
cat('fractional augmentation accepted: ');print(cmb_augment(matrix(1,1,1),1.2,4.4)$y)
cat('registration arity: ');print(getDLLRegisteredRoutines('glmbayes')$.Call$`_glmbayes_EnvelopeBuild_cpp_export`$numParameters)
cat('internal wrapper formals: ');print(length(formals(glmbayes:::.EnvelopeBuild_cpp)))
print(sessionInfo())
